const { db, admin } = require('../config/firebase');

// Firestore 'in' queries support a maximum of 30 values per query.
const CHUNK_SIZE = 30;

const chunkArray = (arr, size) => {
  const chunks = [];
  for (let i = 0; i < arr.length; i += size) {
    chunks.push(arr.slice(i, i + size));
  }
  return chunks;
};

/**
 * Fetches student documents for the given list of student IDs, chunking the
 * lookup into groups of <= 30 to respect Firestore's 'in' query limit.
 */
const getStudentsByIds = async (studentIds) => {
  if (!Array.isArray(studentIds) || studentIds.length === 0) {
    return [];
  }

  const chunks = chunkArray(studentIds, CHUNK_SIZE);
  const snapshots = await Promise.all(
    chunks.map((chunk) =>
      db.collection('students').where(admin.firestore.FieldPath.documentId(), 'in', chunk).get()
    )
  );

  const students = [];
  snapshots.forEach((snapshot) => {
    snapshot.forEach((doc) => {
      students.push({ id: doc.id, ...doc.data() });
    });
  });

  return students;
};

// The exact belt/stage transition of a batch ("Yellow → Orange"), so the Examiner
// sees the same name as the Admin. Batches made by the current generator store it
// (transitionLabel); older ones are resolved here from the configured fees with the same
// rule as the Admin app (a fee document is the TARGET level, "from" is the previous
// entry - White for Karate's first belt; Silambam's first stage is initial, not a promotion).
const resolveTransitionLabel = async (batch) => {
  if (batch.transitionLabel) return batch.transitionLabel;
  const belt = batch.belt == null ? '' : String(batch.belt).trim();
  if (!belt) return null;
  try {
    const isSilambam = batch.programType === 'SELAMBAM';
    const snap = await db.collection(isSilambam ? 'silambanFees' : 'feeStructure').get();
    const fees = snap.docs.map((d) => d.data()).sort((a, b) => (a.order || 0) - (b.order || 0));
    if (isSilambam) {
      const i = fees.findIndex((f) => String(f.stageNumber) === belt);
      const name = (f) => f.stageName || `Stage ${f.stageNumber}`;
      return i > 0 ? `${name(fees[i - 1])} → ${name(fees[i])}` : (i === 0 ? name(fees[0]) : null);
    }
    const i = fees.findIndex((f) => f.beltColor === belt);
    if (i < 0) return null;
    return `${i === 0 ? 'White' : fees[i - 1].beltColor} → ${fees[i].beltColor}`;
  } catch (e) {
    return null;
  }
};

/**
 * Builds the Examiner-facing batch summary (school/belt-test display names,
 * pending/total student counts) plus the resolved student docs for a batch.
 */
const buildBatchSummary = async (batchDoc) => {
  const batch = batchDoc.data();
  const studentIds = Array.isArray(batch.studentIds) ? batch.studentIds : [];

  let schoolName = 'Unknown School';
  if (batch.schoolId === 'individual') {
    schoolName = 'Individual';
  } else if (batch.schoolId) {
    const schoolDoc = await db.collection('schools').doc(batch.schoolId).get();
    if (schoolDoc.exists) {
      schoolName = schoolDoc.data().name || 'Unknown School';
    }
  }

  let beltTestName = 'Unknown Test';
  if (batch.beltTestId) {
    const beltTestDoc = await db.collection('beltTests').doc(batch.beltTestId).get();
    if (beltTestDoc.exists) {
      beltTestName = beltTestDoc.data().name || 'Unknown Test';
    }
  }

  const transitionLabel = await resolveTransitionLabel(batch);
  const students = await getStudentsByIds(studentIds);
  const pendingCount = students.filter((s) => s.testStatus === 'pending').length;
  const totalStudents = studentIds.length;

  const summary = {
    id: batchDoc.id,
    batchNumber: batch.batchNumber,
    customName: batch.customName ?? null,
    programType: batch.programType,
    schoolId: batch.schoolId,
    isAutoGenerated: batch.isAutoGenerated ?? false,
    code: batch.code,
    belt: batch.belt ?? null,
    transitionLabel,
    status: batch.status ?? null,
    // Badge capacity decided at generation time — independent of totalStudents,
    // which only counts students actually scanned in so far (Dynamic Student
    // Assignment: studentIds starts empty and fills one scan at a time).
    maxSize: batch.maxSize ?? totalStudents,
    schoolName,
    beltTestName,
    totalStudents,
    pendingCount
  };

  return { summary, students };
};

/**
 * Capacity model. `maxSize` is the batch's configured capacity and is never
 * reduced. `allocatedCount` (maintained transactionally by /allocate) is the
 * total slots examiners have reserved; `allocatedAssigned` is how many
 * students were added through those reservations. Students assigned before
 * allocations existed (or by Admin) are "legacy" and also occupy capacity.
 */
const computeCapacity = (batch) => {
  const total = Number.isInteger(batch.maxSize) ? batch.maxSize : (Array.isArray(batch.studentIds) ? batch.studentIds.length : 0);
  const allocated = batch.allocatedCount || 0;
  const assigned = Array.isArray(batch.studentIds) ? batch.studentIds.length : 0;
  const legacy = Math.max(0, assigned - (batch.allocatedAssigned || 0));
  return { total, allocated, legacy, available: Math.max(0, total - allocated - legacy) };
};

const allocationsRef = (batchId) => db.collection('batches').doc(batchId).collection('allocations');

const toMyAllocation = (alloc) => {
  const studentIds = alloc && Array.isArray(alloc.studentIds) ? alloc.studentIds : [];
  const quantity = (alloc && alloc.quantity) || 0;
  return { quantity, assigned: studentIds.length, remaining: Math.max(0, quantity - studentIds.length), studentIds, started: !!(alloc && alloc.examStartedAt) };
};

const buildCapacityView = (batch, alloc) => ({ ...computeCapacity(batch), mine: toMyAllocation(alloc) });

module.exports = { getStudentsByIds, buildBatchSummary, computeCapacity, allocationsRef, toMyAllocation, buildCapacityView, CHUNK_SIZE };
