const { db, admin } = require('../config/firebase');

// Firestore 'in' queries support a maximum of 30 values per query.
const CHUNK_SIZE = 30;

const chunkArray = (arr, size) => {
  const chunks = [];
  for (let i = 0; i < arr.length; i += size) {
    chunks.push(arr.slice(i, i + size));
  }
  return chunks;
};

/**
 * Fetches student documents for the given list of student IDs, chunking the
 * lookup into groups of <= 30 to respect Firestore's 'in' query limit.
 */
const getStudentsByIds = async (studentIds) => {
  if (!Array.isArray(studentIds) || studentIds.length === 0) {
    return [];
  }

  const chunks = chunkArray(studentIds, CHUNK_SIZE);
  const snapshots = await Promise.all(
    chunks.map((chunk) =>
      db.collection('students').where(admin.firestore.FieldPath.documentId(), 'in', chunk).get()
    )
  );

  const students = [];
  snapshots.forEach((snapshot) => {
    snapshot.forEach((doc) => {
      students.push({ id: doc.id, ...doc.data() });
    });
  });

  return students;
};

/**
 * Builds the Examiner-facing batch summary (school/belt-test display names,
 * pending/total student counts) plus the resolved student docs for a batch.
 */
const buildBatchSummary = async (batchDoc) => {
  const batch = batchDoc.data();
  const studentIds = Array.isArray(batch.studentIds) ? batch.studentIds : [];

  let schoolName = 'Unknown School';
  if (batch.schoolId === 'individual') {
    schoolName = 'Individual';
  } else if (batch.schoolId) {
    const schoolDoc = await db.collection('schools').doc(batch.schoolId).get();
    if (schoolDoc.exists) {
      schoolName = schoolDoc.data().name || 'Unknown School';
    }
  }

  let beltTestName = 'Unknown Test';
  if (batch.beltTestId) {
    const beltTestDoc = await db.collection('beltTests').doc(batch.beltTestId).get();
    if (beltTestDoc.exists) {
      beltTestName = beltTestDoc.data().name || 'Unknown Test';
    }
  }

  const students = await getStudentsByIds(studentIds);
  const pendingCount = students.filter((s) => s.testStatus === 'pending').length;
  const totalStudents = studentIds.length;

  const summary = {
    id: batchDoc.id,
    batchNumber: batch.batchNumber,
    customName: batch.customName ?? null,
    programType: batch.programType,
    schoolId: batch.schoolId,
    isAutoGenerated: batch.isAutoGenerated ?? false,
    code: batch.code,
    schoolName,
    beltTestName,
    totalStudents,
    pendingCount
  };

  return { summary, students };
};

module.exports = { getStudentsByIds, buildBatchSummary, CHUNK_SIZE };
