export { default as karateFamilyPose01 } from './gallery/karate/karate-family-pose-01.webp';
export { default as karateFamilyPose02 } from './gallery/karate/karate-family-pose-02.webp';
export { default as karateGroupTraining01 } from './gallery/karate/karate-group-training-01.webp';
export { default as karateIndoorsPose01 } from './gallery/karate/karate-indoors-pose-01.jpg';
export { default as karateKneelingBlock01 } from './gallery/karate/karate-kneeling-block-01.webp';
export { default as karateKneelingPose01 } from './gallery/karate/karate-kneeling-pose-01.webp';
export { default as karateLowBlock01 } from './gallery/karate/karate-low-block-01.webp';
export { default as karateLowStance01 } from './gallery/karate/karate-low-stance-01.webp';
export { default as karateLowStance02 } from './gallery/karate/karate-low-stance-02.webp';
export { default as karateStance01 } from './gallery/karate/karate-stance-01.webp';
export { default as maduvuKneelingPose01 } from './gallery/maduvu/maduvu-kneeling-pose-01.webp';
export { default as maduvuKneelingPose02 } from './gallery/maduvu/maduvu-kneeling-pose-02.webp';
export { default as maduvuKneelingPose03 } from './gallery/maduvu/maduvu-kneeling-pose-03.webp';
export { default as maduvuStandingPose01 } from './gallery/maduvu/maduvu-standing-pose-01.webp';
export { default as maduvuStandingPose02 } from './gallery/maduvu/maduvu-standing-pose-02.webp';
export { default as silambamAcrobatics01 } from './gallery/silambam/silambam-acrobatics-01.webp';
export { default as silambamAcrobatics02 } from './gallery/silambam/silambam-acrobatics-02.webp';
export { default as silambamAcrobatics03 } from './gallery/silambam/silambam-acrobatics-03.webp';
export { default as silambamAcrobatics04 } from './gallery/silambam/silambam-acrobatics-04.webp';
export { default as silambamAcrobatics05 } from './gallery/silambam/silambam-acrobatics-05.webp';
export { default as silambamActionShot01 } from './gallery/silambam/silambam-action-shot-01.webp';
export { default as silambamBendingPose01 } from './gallery/silambam/silambam-bending-pose-01.webp';
export { default as silambamCranePose01 } from './gallery/silambam/silambam-crane-pose-01.webp';
export { default as silambamCranePose02 } from './gallery/silambam/silambam-crane-pose-02.webp';
export { default as silambamCranePose03 } from './gallery/silambam/silambam-crane-pose-03.webp';
export { default as silambamCranePose04 } from './gallery/silambam/silambam-crane-pose-04.webp';
export { default as silambamCranePose05 } from './gallery/silambam/silambam-crane-pose-05.webp';
export { default as silambamCranePose06 } from './gallery/silambam/silambam-crane-pose-06.webp';
export { default as karateAction01 } from './gallery/karate/karate-action-01.webp';
export { default as silambamDoubleStick02 } from './gallery/silambam/silambam-double-stick-02.webp';
export { default as silambamDoubleStick03 } from './gallery/silambam/silambam-double-stick-03.webp';
export { default as silambamDoubleStick04 } from './gallery/silambam/silambam-double-stick-04.webp';
export { default as silambamGroupCombatPose01 } from './gallery/silambam/silambam-group-combat-pose-01.webp';
export { default as silambamGroupCombatPose02 } from './gallery/silambam/silambam-group-combat-pose-02.webp';
export { default as silambamGroupCraneOverhead01 } from './gallery/silambam/silambam-group-crane-overhead-01.webp';
export { default as silambamGroupCranePose01 } from './gallery/silambam/silambam-group-crane-pose-01.webp';
export { default as silambamGroupCranePose02 } from './gallery/silambam/silambam-group-crane-pose-02.webp';
export { default as silambamGroupCranePose03 } from './gallery/silambam/silambam-group-crane-pose-03.webp';
export { default as silambamGroupCranePose04 } from './gallery/silambam/silambam-group-crane-pose-04.webp';
export { default as silambamGroupCranePose05 } from './gallery/silambam/silambam-group-crane-pose-05.webp';
export { default as silambamGroupCranePose06 } from './gallery/silambam/silambam-group-crane-pose-06.webp';
export { default as silambamGroupCranePose07 } from './gallery/silambam/silambam-group-crane-pose-07.webp';
export { default as silambamGroupCranePose08 } from './gallery/silambam/silambam-group-crane-pose-08.webp';
export { default as silambamGroupCranePose09 } from './gallery/silambam/silambam-group-crane-pose-09.webp';
export { default as silambamGroupCrouch01 } from './gallery/silambam/silambam-group-crouch-01.webp';
export { default as silambamGroupKneelingBlock01 } from './gallery/silambam/silambam-group-kneeling-block-01.webp';
export { default as silambamGroupKneelingBlock02 } from './gallery/silambam/silambam-group-kneeling-block-02.webp';
export { default as silambamGroupKneelingBlock03 } from './gallery/silambam/silambam-group-kneeling-block-03.webp';
export { default as silambamGroupKneelingBlock04 } from './gallery/silambam/silambam-group-kneeling-block-04.webp';
export { default as silambamGroupKneelingCombat01 } from './gallery/silambam/silambam-group-kneeling-combat-01.webp';
export { default as silambamGroupKneelingHorizontal01 } from './gallery/silambam/silambam-group-kneeling-horizontal-01.webp';
export { default as silambamGroupKneelingOverhead01 } from './gallery/silambam/silambam-group-kneeling-overhead-01.webp';
export { default as silambamGroupKneelingOverhead02 } from './gallery/silambam/silambam-group-kneeling-overhead-02.webp';
export { default as silambamGroupLegRaise01 } from './gallery/silambam/silambam-group-leg-raise-01.webp';
export { default as silambamGroupLegRaiseOverhead01 } from './gallery/silambam/silambam-group-leg-raise-overhead-01.webp';
export { default as silambamGroupLinePose01 } from './gallery/silambam/silambam-group-line-pose-01.webp';
export { default as silambamGroupLowPose01 } from './gallery/silambam/silambam-group-low-pose-01.webp';
export { default as silambamGroupLunge01 } from './gallery/silambam/silambam-group-lunge-01.webp';
export { default as silambamGroupPose02 } from './gallery/silambam/silambam-group-pose-02.webp';
export { default as silambamGroupRunningPose01 } from './gallery/silambam/silambam-group-running-pose-01.webp';
export { default as silambamGroupStandingLine01 } from './gallery/silambam/silambam-group-standing-line-01.webp';
export { default as silambamGroupStandingLine02 } from './gallery/silambam/silambam-group-standing-line-02.webp';
export { default as silambamJumpTraining01 } from './gallery/silambam/silambam-jump-training-01.webp';
export { default as silambamJumpTraining02 } from './gallery/silambam/silambam-jump-training-02.webp';
export { default as silambamJumpTraining03 } from './gallery/silambam/silambam-jump-training-03.webp';
export { default as silambamJumpTraining05 } from './gallery/silambam/silambam-jump-training-05.webp';
export { default as silambamJumpingStickCombat01 } from './gallery/silambam/silambam-jumping-stick-combat-01.webp';
export { default as silambamKneelingBlock01 } from './gallery/silambam/silambam-kneeling-block-01.webp';
export { default as silambamKneelingOverhead01 } from './gallery/silambam/silambam-kneeling-overhead-01.webp';
export { default as silambamKneelingPose01 } from './gallery/silambam/silambam-kneeling-pose-01.webp';
export { default as silambamStickCombat01 } from './gallery/silambam/silambam-stick-combat-01.webp';
export { default as silambamStickCombat02 } from './gallery/silambam/silambam-stick-combat-02.webp';
export { default as silambamStickCombat03 } from './gallery/silambam/silambam-stick-combat-03.webp';
export { default as silambamStickCombat04 } from './gallery/silambam/silambam-stick-combat-04.webp';
export { default as silambamStickCombat05 } from './gallery/silambam/silambam-stick-combat-05.webp';
export { default as silambamStickCombat06 } from './gallery/silambam/silambam-stick-combat-06.webp';
export { default as silambamStickCombat07 } from './gallery/silambam/silambam-stick-combat-07.webp';
export { default as silambamStickCombat08 } from './gallery/silambam/silambam-stick-combat-08.webp';
export { default as silambamStickCombat09 } from './gallery/silambam/silambam-stick-combat-09.webp';
export { default as silambamStickCombat10 } from './gallery/silambam/silambam-stick-combat-10.webp';
export { default as silambamStickCombat11 } from './gallery/silambam/silambam-stick-combat-11.webp';
export { default as silambamStickCombat12 } from './gallery/silambam/silambam-stick-combat-12.webp';
export { default as silambamStickCombat13 } from './gallery/silambam/silambam-stick-combat-13.webp';
export { default as silambamStickCombat14 } from './gallery/silambam/silambam-stick-combat-14.webp';
export { default as silambamStickCombat15 } from './gallery/silambam/silambam-stick-combat-15.webp';
export { default as silambamStickCombat16 } from './gallery/silambam/silambam-stick-combat-16.webp';
export { default as silambamStickCombat17 } from './gallery/silambam/silambam-stick-combat-17.webp';
export { default as silambamStickCross01 } from './gallery/silambam/silambam-stick-cross-01.webp';
export { default as silambamStickPose01 } from './gallery/silambam/silambam-stick-pose-01.webp';
export { default as silambamStickPose02 } from './gallery/silambam/silambam-stick-pose-02.webp';
export { default as silambamStickPose03 } from './gallery/silambam/silambam-stick-pose-03.webp';
export { default as karateTournament01 } from './gallery/karate/karate-tournament-01.jpg';
export { default as karateTournament02 } from './gallery/karate/karate-tournament-02.webp';
export { default as karateTournament03 } from './gallery/karate/karate-tournament-03.webp';
export { default as karateTournament04 } from './gallery/karate/karate-tournament-04.jpg';
export { default as karateTournament05 } from './gallery/karate/karate-tournament-05.webp';
export { default as karateTournament06 } from './gallery/karate/karate-tournament-06.webp';
export { default as karateTournament07 } from './gallery/karate/karate-tournament-07.webp';
export { default as karateTournament08 } from './gallery/karate/karate-tournament-08.webp';
export { default as karateTournament09 } from './gallery/karate/karate-tournament-09.jpg';
export { default as karateTournament10 } from './gallery/karate/karate-tournament-10.jpg';
export { default as karateTournament11 } from './gallery/karate/karate-tournament-11.jpg';
export { default as karateTournament12 } from './gallery/karate/karate-tournament-12.jpg';
export { default as karateTournament13 } from './gallery/karate/karate-tournament-13.jpg';
export { default as karateTournament14 } from './gallery/karate/karate-tournament-14.jpg';
export { default as karateTournament15 } from './gallery/karate/karate-tournament-15.jpg';
export { default as karateTournament16 } from './gallery/karate/karate-tournament-16.webp';
export { default as karateTournament17 } from './gallery/karate/karate-tournament-17.webp';
export { default as karateTournament18 } from './gallery/karate/karate-tournament-18.webp';
export { default as karateTournament19 } from './gallery/karate/karate-tournament-19.webp';
export { default as karateTournament20 } from './gallery/karate/karate-tournament-20.webp';
export { default as karateTournament21 } from './gallery/karate/karate-tournament-21.webp';
export { default as karateBeltYellow } from './mascots/karate/Yellow Belt.png';
export { default as karateBeltOrange } from './mascots/karate/Orange Belt.png';
export { default as karateBeltBlue } from './mascots/karate/Blue Belt.png';
export { default as karateBeltGreen } from './mascots/karate/Green Belt.png';
export { default as karateBeltBrown } from './mascots/karate/Brown Belt.png';
export { default as karateBeltBlack } from './mascots/karate/Black Belt.png';
export { default as silambamStage1 } from './mascots/silambam/Stage 1.png';
export { default as silambamStage2 } from './mascots/silambam/Stage 2.png';
export { default as silambamStage3 } from './mascots/silambam/Stage 3.png';
export { default as silambamStage4 } from './mascots/silambam/Stage 4.png';
export { default as silambamStage5 } from './mascots/silambam/Stage 5.png';
export { default as silambamStage6 } from './mascots/silambam/Stage 6.png';
export { default as silambamStage7 } from './mascots/silambam/Stage 7.png';
export { default as silambamStage8 } from './mascots/silambam/Stage 8.png';
export { default as silambamStage9 } from './mascots/silambam/Stage 9.png';
export { default as silambamStage10 } from './mascots/silambam/Stage 10.png';
export { default as karateProgression } from './misc/karate-progression.jpg';
export { default as silambamProgression } from './misc/silambam-progression.jpg';