// Examiner API client — talks to the backend's public (no-login) Examiner
// endpoints under /api/examiner/*. Mirrors the `${VITE_API_BASE_URL}/api/...`
// convention used elsewhere (see WhatsAppResultsSender.tsx) and the
// fetchJson() contract from utils/apiFetch.ts (reads body as text first,
// never throws on a non-2xx JSON response — callers check `data.success`).
//
// Auth model: a batch-scoped JWT is issued by POST /verify-code (no auth
// header needed for that call) and then persisted by the caller into
// localStorage under `examinerToken`. Every other Examiner call attaches it
// as `Authorization: Bearer <token>` automatically. There is no Examiner
// *account* — the token is the only credential, and it is scoped to the one
// batch that was verified.
import { fetchJson } from "../utils/apiFetch";

const EXAMINER_TOKEN_KEY = "examinerToken";
const EXAMINER_BATCH_KEY = "examinerBatch";

export interface ExaminerBatch {
  id: string;
  batchNumber: number;
  customName: string | null;
  programType: "KARATE" | "SELAMBAM";
  schoolId: string;
  isAutoGenerated: boolean;
  code: string;
  belt?: string | null;
  /** Stored batch status (waiting | filling | ongoing | completed). */
  status?: string | null;
  /** Badge capacity decided at generation time (independent of totalStudents). */
  maxSize?: number;
  schoolName: string;
  beltTestName: string;
  totalStudents: number;
  pendingCount: number;
}

export interface ExaminerStudent {
  id: string;
  name: string;
  gender: string;
  school: string;
  beltLevel: string | null;
  beltIndex: number | null;
  stageLevel: number | null;
  programType: "KARATE" | "SELAMBAM";
  testStatus: "pending" | "passed" | "failed";
}

export interface ExaminerCapacity {
  /** Configured batch capacity - never reduced by allocations. */
  total: number;
  /** Slots reserved by all examiners together. */
  allocated: number;
  /** Capacity still free for any examiner to reserve (server-computed). */
  available: number;
  /** This examiner's own reservation. */
  mine: { quantity: number; assigned: number; remaining: number; studentIds: string[]; started?: boolean };
}

export interface VerifyCodeResponse {
  success: boolean;
  token?: string;
  batch?: ExaminerBatch;
  message?: string;
}

export interface ExaminerStudentsResponse {
  success: boolean;
  students?: ExaminerStudent[];
  batch?: ExaminerBatch;
  capacity?: ExaminerCapacity;
  message?: string;
}

export interface AllocateSlotsResponse {
  success: boolean;
  replayed?: boolean;
  /** Present only when a recovery key was just issued - saved as a local hint. */
  recovery?: { allocationId: string; recoveryKey: string } | null;
  capacity?: ExaminerCapacity;
  message?: string;
}

export interface SubmitExaminerScorePayload {
  studentId: string;
  technicalScore: number;
  athleticScore: number;
  scoringResults: unknown;
  subCategoryResults: unknown;
  percentage: number;
  result: "passed" | "failed";
  examinerRemarks?: string;
  lessonNumbers?: unknown;
}

export interface SubmitExaminerScoreResponse {
  success: boolean;
  /** True when this very save completed the batch (server-verified). */
  batchCompleted?: boolean;
  batchStatus?: string;
  student?: {
    id: string;
    testStatus: string;
    percentage: number;
    result: string;
  };
  message?: string;
}

function getExaminerBaseUrl(): string {
  return `${import.meta.env.VITE_API_BASE_URL}/api/examiner`;
}

/**
 * Thin wrapper around fetchJson() that attaches the stored Examiner token
 * (unless this is the initial verify-code call, which has none yet) and
 * clears Examiner localStorage on a 401 so the calling screen can redirect.
 * Does NOT navigate itself — this is a plain service module, not a hook.
 */
async function examinerFetch<T = any>(
  path: string,
  options: RequestInit & { skipAuth?: boolean } = {},
): Promise<{ ok: boolean; status: number; data: T }> {
  const { skipAuth, headers, ...rest } = options;
  const token = localStorage.getItem(EXAMINER_TOKEN_KEY);

  const finalHeaders: Record<string, string> = {
    "Content-Type": "application/json",
    ...((headers as Record<string, string>) || {}),
  };

  if (!skipAuth && token) {
    finalHeaders["Authorization"] = `Bearer ${token}`;
  }

  const result = await fetchJson<T>(`${getExaminerBaseUrl()}${path}`, {
    ...rest,
    headers: finalHeaders,
  });

  if (result.status === 401) {
    localStorage.removeItem(EXAMINER_TOKEN_KEY);
    localStorage.removeItem(EXAMINER_BATCH_KEY);
  }

  // Backend error responses (via withErrorHandler) nest the message as
  // `error.message`, not a top-level `message` — normalize here so every
  // caller can just read `data.message` without knowing that shape.
  const data = result.data as any;
  if (data && data.success === false && !data.message && data.error?.message) {
    data.message = data.error.message;
  }

  return result;
}

export async function verifyExaminerCode(
  code: string,
  batchId?: string,
): Promise<{ ok: boolean; status: number; data: VerifyCodeResponse }> {
  const attempt = () =>
    examinerFetch<VerifyCodeResponse>("/verify-code", {
      method: "POST",
      skipAuth: true,
      body: JSON.stringify({ code, batchId }),
    });
  try {
    return await attempt();
  } catch (err) {
    // fetchJson() *throws* (rather than resolving with ok:false) only for a
    // network failure or a non-JSON response body — both symptomatic of a
    // transient blip (cold start, a dropped packet on a flaky field
    // connection) rather than a real "wrong code" result, which always comes
    // back as a normal JSON {success:false} response and resolves normally
    // without hitting this catch. Verifying a code is read-only, so retrying
    // it once is safe — this is the same "try again in a moment" the error
    // message already suggests, just done automatically before showing it.
    await new Promise((resolve) => setTimeout(resolve, 1200));
    return attempt();
  }
}

export async function getExaminerStudents(): Promise<{
  ok: boolean;
  status: number;
  data: ExaminerStudentsResponse;
}> {
  return examinerFetch<ExaminerStudentsResponse>("/students", {
    method: "GET",
  });
}

export async function submitExaminerScore(
  payload: SubmitExaminerScorePayload,
): Promise<{ ok: boolean; status: number; data: SubmitExaminerScoreResponse }> {
  return examinerFetch<SubmitExaminerScoreResponse>("/submit-score", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

// Reserve `quantity` slots for this examiner. `requestId` is generated once
// per user action by the caller and reused on any retry, so a double-click or
// network retry is applied by the server only once.
export async function allocateExaminerSlots(
  quantity: number,
  requestId: string,
  examinerName?: string,
): Promise<{ ok: boolean; status: number; data: AllocateSlotsResponse }> {
  return examinerFetch<AllocateSlotsResponse>("/allocate", {
    method: "POST",
    body: JSON.stringify({ quantity, requestId, examinerName }),
  });
}

// -- Session recovery ---------------------------------------------------------
// Local Storage only holds a *hint* (allocation id + a random per-allocation
// recovery key) per batch. The backend decides whether it is valid; clearing
// it never releases anything - the allocation stays on the server and can be
// found again by the name used when reserving.
export interface RecoveryHint {
  batchId: string;
  schoolId: string;
  allocationId: string;
  recoveryKey: string;
}

const recoveryStorageKey = (batchId: string) => `examinerRecovery:v1:${batchId}`;

export function loadRecoveryHint(batch: { id: string; schoolId: string }): RecoveryHint | null {
  try {
    const raw = localStorage.getItem(recoveryStorageKey(batch.id));
    if (!raw) return null;
    const h = JSON.parse(raw);
    // Never reuse a hint across batches/schools, and ignore anything malformed.
    if (
      h && typeof h.allocationId === "string" && typeof h.recoveryKey === "string" &&
      h.batchId === batch.id && h.schoolId === batch.schoolId
    ) {
      return h as RecoveryHint;
    }
  } catch {
    /* corrupted - treated as missing */
  }
  return null;
}

export function saveRecoveryHint(batch: { id: string; schoolId: string }, allocationId: string, recoveryKey: string) {
  try {
    const hint: RecoveryHint = { batchId: batch.id, schoolId: batch.schoolId, allocationId, recoveryKey };
    localStorage.setItem(recoveryStorageKey(batch.id), JSON.stringify(hint));
  } catch {
    /* storage unavailable - recovery by name still works */
  }
}

export function clearRecoveryHint(batchId: string) {
  try {
    localStorage.removeItem(recoveryStorageKey(batchId));
  } catch {
    /* ignore */
  }
}

export interface RecoverResponse {
  success: boolean;
  result?: "recovered" | "invalid" | "no_allocation" | "capacity_exhausted";
  token?: string;
  allocationId?: string;
  recoveryKey?: string | null;
  capacity?: ExaminerCapacity;
  message?: string;
}

export async function recoverExaminerSession(payload: {
  allocationId?: string;
  recoveryKey?: string;
  examinerName?: string;
}): Promise<{ ok: boolean; status: number; data: RecoverResponse }> {
  return examinerFetch<RecoverResponse>("/recover", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export interface CapacityResponse {
  success: boolean;
  capacity?: ExaminerCapacity;
  message?: string;
}

// Un-assign a mistakenly added student before the examination starts. The
// backend re-checks ownership and the started state; the student's record is
// kept and the slot returns to this examiner's remaining slots.
export async function removeExaminerStudent(
  studentId: string,
): Promise<{ ok: boolean; status: number; data: CapacityResponse }> {
  return examinerFetch<CapacityResponse>("/remove-student", {
    method: "POST",
    body: JSON.stringify({ studentId }),
  });
}

// Marks this examiner's session as started (locks removal server-side).
export async function startExaminerExam(): Promise<{ ok: boolean; status: number; data: CapacityResponse }> {
  return examinerFetch<CapacityResponse>("/start-exam", { method: "POST" });
}

export interface ScanStudentResponse {
  success: boolean;
  student?: ExaminerStudent;
  message?: string;
}

// Dynamic Student Assignment — called once per scanned/entered student QR.
// `qrValue` is whatever the scanner (or a manual-entry fallback) read; the
// backend parses it the same way the existing admin QR Scanner does, so any
// already-printed student QR works without changes.
export async function scanExaminerStudent(
  qrValue: string,
): Promise<{ ok: boolean; status: number; data: ScanStudentResponse }> {
  return examinerFetch<ScanStudentResponse>("/scan-student", {
    method: "POST",
    body: JSON.stringify({ qrValue }),
  });
}
