// Examiner API client — talks to the backend's public (no-login) Examiner
// endpoints under /api/examiner/*. Mirrors the `${VITE_API_BASE_URL}/api/...`
// convention used elsewhere (see WhatsAppResultsSender.tsx) and the
// fetchJson() contract from utils/apiFetch.ts (reads body as text first,
// never throws on a non-2xx JSON response — callers check `data.success`).
//
// Auth model: a batch-scoped JWT is issued by POST /verify-code (no auth
// header needed for that call) and then persisted by the caller into
// localStorage under `examinerToken`. Every other Examiner call attaches it
// as `Authorization: Bearer <token>` automatically. There is no Examiner
// *account* — the token is the only credential, and it is scoped to the one
// batch that was verified.
import { fetchJson } from "../utils/apiFetch";

const EXAMINER_TOKEN_KEY = "examinerToken";
const EXAMINER_BATCH_KEY = "examinerBatch";

export interface ExaminerBatch {
  id: string;
  batchNumber: number;
  customName: string | null;
  programType: "KARATE" | "SELAMBAM";
  schoolId: string;
  isAutoGenerated: boolean;
  code: string;
  schoolName: string;
  beltTestName: string;
  totalStudents: number;
  pendingCount: number;
}

export interface ExaminerStudent {
  id: string;
  name: string;
  gender: string;
  school: string;
  beltLevel: string | null;
  beltIndex: number | null;
  stageLevel: number | null;
  programType: "KARATE" | "SELAMBAM";
  testStatus: "pending" | "passed" | "failed";
}

export interface VerifyCodeResponse {
  success: boolean;
  token?: string;
  batch?: ExaminerBatch;
  message?: string;
}

export interface ExaminerStudentsResponse {
  success: boolean;
  students?: ExaminerStudent[];
  batch?: ExaminerBatch;
  message?: string;
}

export interface SubmitExaminerScorePayload {
  studentId: string;
  technicalScore: number;
  athleticScore: number;
  scoringResults: unknown;
  subCategoryResults: unknown;
  percentage: number;
  result: "passed" | "failed";
  examinerRemarks?: string;
  lessonNumbers?: unknown;
}

export interface SubmitExaminerScoreResponse {
  success: boolean;
  student?: {
    id: string;
    testStatus: string;
    percentage: number;
    result: string;
  };
  message?: string;
}

function getExaminerBaseUrl(): string {
  return `${import.meta.env.VITE_API_BASE_URL}/api/examiner`;
}

/**
 * Thin wrapper around fetchJson() that attaches the stored Examiner token
 * (unless this is the initial verify-code call, which has none yet) and
 * clears Examiner localStorage on a 401 so the calling screen can redirect.
 * Does NOT navigate itself — this is a plain service module, not a hook.
 */
async function examinerFetch<T = any>(
  path: string,
  options: RequestInit & { skipAuth?: boolean } = {},
): Promise<{ ok: boolean; status: number; data: T }> {
  const { skipAuth, headers, ...rest } = options;
  const token = localStorage.getItem(EXAMINER_TOKEN_KEY);

  const finalHeaders: Record<string, string> = {
    "Content-Type": "application/json",
    ...((headers as Record<string, string>) || {}),
  };

  if (!skipAuth && token) {
    finalHeaders["Authorization"] = `Bearer ${token}`;
  }

  const result = await fetchJson<T>(`${getExaminerBaseUrl()}${path}`, {
    ...rest,
    headers: finalHeaders,
  });

  if (result.status === 401) {
    localStorage.removeItem(EXAMINER_TOKEN_KEY);
    localStorage.removeItem(EXAMINER_BATCH_KEY);
  }

  // Backend error responses (via withErrorHandler) nest the message as
  // `error.message`, not a top-level `message` — normalize here so every
  // caller can just read `data.message` without knowing that shape.
  const data = result.data as any;
  if (data && data.success === false && !data.message && data.error?.message) {
    data.message = data.error.message;
  }

  return result;
}

export async function verifyExaminerCode(
  code: string,
): Promise<{ ok: boolean; status: number; data: VerifyCodeResponse }> {
  const attempt = () =>
    examinerFetch<VerifyCodeResponse>("/verify-code", {
      method: "POST",
      skipAuth: true,
      body: JSON.stringify({ code }),
    });
  try {
    return await attempt();
  } catch (err) {
    // fetchJson() *throws* (rather than resolving with ok:false) only for a
    // network failure or a non-JSON response body — both symptomatic of a
    // transient blip (cold start, a dropped packet on a flaky field
    // connection) rather than a real "wrong code" result, which always comes
    // back as a normal JSON {success:false} response and resolves normally
    // without hitting this catch. Verifying a code is read-only, so retrying
    // it once is safe — this is the same "try again in a moment" the error
    // message already suggests, just done automatically before showing it.
    await new Promise((resolve) => setTimeout(resolve, 1200));
    return attempt();
  }
}

export async function getExaminerStudents(): Promise<{
  ok: boolean;
  status: number;
  data: ExaminerStudentsResponse;
}> {
  return examinerFetch<ExaminerStudentsResponse>("/students", {
    method: "GET",
  });
}

export async function submitExaminerScore(
  payload: SubmitExaminerScorePayload,
): Promise<{ ok: boolean; status: number; data: SubmitExaminerScoreResponse }> {
  return examinerFetch<SubmitExaminerScoreResponse>("/submit-score", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}
